# This file was generated by GoReleaser. DO NOT EDIT.
cask "ant" do
  version "1.7.0"

  on_macos do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_amd64.zip"
      sha256 "83b577f9b6b9002623fb701a2c86cd48598ff71034e04c7dffb21fbb201dd765"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_arm64.zip"
      sha256 "a69bdf90e91d3cfa7f63f9ce21994107d2e54cd95b517d2b4f94f05d34773c8e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_amd64.tar.gz"
      sha256 "71194cceefeca2dcfcfbf6d21f69f135a70ba3f17bf785dedf3e084411b1524b"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_arm64.tar.gz"
      sha256 "99064617d0246c2093480818075c269cbf45d819f1bb3f5c0364cbeba69ad162"
    end
  end

  name "ant"
  desc "CLI for the Claude Platform"
  homepage "anthropic.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ant"
  manpage "man/man1/ant.1.gz"
  bash_completion "completions/ant.bash"
  fish_completion "completions/ant.fish"
  zsh_completion "completions/ant.zsh"

  # No zap stanza required

end
