# This file was generated by GoReleaser. DO NOT EDIT.
cask "ant" do
  version "1.5.0"

  on_macos do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_amd64.zip"
      sha256 "89db467af523a2709f459778dcab26552b80928699b6ec0ef36058d44f4fedeb"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_arm64.zip"
      sha256 "3e75e763417eb693bb60bbb5eb5994624b6213b4aaae29971cfdcac19e0d9730"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_amd64.tar.gz"
      sha256 "4c77e0bad4b2e3b2ce28c843e96ba484188a06f805a1daaeb43ee2c4495b412a"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_arm64.tar.gz"
      sha256 "678036ee1a79b86c76d801b5c48ec75e2e065ae5c782439609e053cff6878415"
    end
  end

  name "ant"
  desc "CLI for the Claude Platform"
  homepage "anthropic.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ant"
  manpage "man/man1/ant.1.gz"
  bash_completion "completions/ant.bash"
  fish_completion "completions/ant.fish"
  zsh_completion "completions/ant.zsh"

  # No zap stanza required

end
