# This file was generated by GoReleaser. DO NOT EDIT.
cask "ant" do
  version "1.3.2"

  on_macos do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_amd64.zip"
      sha256 "b82772df8b6b0f49ee055053cc7fb30d43a1aec28d3aec61aaf952f8f71cb49a"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_macos_arm64.zip"
      sha256 "c6ebc46d7be34441e1d60bac19bc3fe2850151f86727404ab591bccfa0e76b99"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_amd64.tar.gz"
      sha256 "173959e9d2fc2df803e15c1ee9ee8c9d61d1a02b02763630faddf5fd9c8dbb44"
    end
    on_arm do
      url "https://github.com/anthropics/anthropic-cli/releases/download/v#{version}/ant_#{version}_linux_arm64.tar.gz"
      sha256 "2234464cff215e81e3711647e370ce90801a176db1a922b15c672d391cdd84e6"
    end
  end

  name "ant"
  desc "CLI for the Claude Platform"
  homepage "anthropic.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ant"
  manpage "man/man1/ant.1.gz"
  bash_completion "completions/ant.bash"
  fish_completion "completions/ant.fish"
  zsh_completion "completions/ant.zsh"

  # No zap stanza required

end
